sudo: required # need superlevel permissions to execute this build
services:
  - docker # will essentially install copy of docker into our running container.
before_install: # series of commands that get executed before tests are run.
  - docker build -t michaelsking1993/docker-react -f Dockerfile.dev .

script: # should contain all commands needed to run our test suite.
  - docker run michaelsking1993/docker-react npm run test -- --coverage